# Generated by Django 4.1.3 on 2022-11-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'ModeloRam',
            },
        ),
        migrations.AlterField(
            model_name='ram',
            name='Modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.modeloram'),
        ),
    ]
