# Generated by Django 4.1.3 on 2022-11-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0002_modeloram_alter_ram_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='Serial',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
