# Generated by Django 4.1.3 on 2022-11-21 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_alter_ram_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licencia',
            name='modelo',
        ),
        migrations.AddField(
            model_name='licencia',
            name='Software',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
