# Generated by Django 4.1.3 on 2022-11-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0005_remove_telefono_fijo_modelo_telefono_fijo_extension_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='Periferico',
            new_name='Otro_Elemento',
        ),
    ]
