# Generated by Django 4.1.3 on 2022-11-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_rename_periferico_asignacion_otro_elemento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analista_Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=200)),
                ('Apellidos', models.CharField(max_length=200)),
                ('Correo', models.EmailField(max_length=100, unique=True)),
                ('Numero_Celular', models.CharField(default='', max_length=70)),
            ],
            options={
                'verbose_name_plural': 'Analista_Gestion',
            },
        ),
        migrations.RemoveField(
            model_name='asignacion',
            name='Acta',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Fecha_Final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='Fecha_Inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
