# Generated by Django 4.1.3 on 2022-11-21 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0008_asignacion_analista_a_cargo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Periferico',
            new_name='Otros_Elementos',
        ),
    ]
