# Generated by Django 4.1.3 on 2022-11-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0010_rename_modelo_otros_elementos_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otros_elementos',
            options={'verbose_name_plural': 'Otros_Elementos'},
        ),
    ]
