# Generated by Django 4.1.3 on 2022-11-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0011_alter_otros_elementos_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacion',
            old_name='Telefono_fijo',
            new_name='Extencion',
        ),
        migrations.AddField(
            model_name='cpu',
            name='Nombre_Equipo',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='Nombre_Equipo',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
    ]
