# Generated by Django 4.1.3 on 2022-11-21 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0012_rename_telefono_fijo_asignacion_extencion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Telefono_fijo',
            new_name='Extension',
        ),
    ]
