# Generated by Django 4.1.3 on 2022-11-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0013_rename_telefono_fijo_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta_Grafica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modelo', models.CharField(max_length=40, unique=True)),
                ('Tipo_de_Interfaz', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Tarjeta_Grafica',
            },
        ),
    ]
